version: '3.7'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      # 4000 is a port for Cube.js API
      - 4000:4000
      # 3000 is a port for Playground web server
      # it is available only in dev mode
      - 3001:3001
    env_file: .env
    volumes:
      - ./schema:/cube/conf/schema
      - ./cube.js:/cube/conf/cube.js
      - ./certificateRequest.pem:/home/certificateRequest.pem
    depends_on: [mongobi]
  mongobi:
    image: test/mongobi
    restart: always
    volumes:
      # - "./schema:/home/mongobi/schema.drdl" #Uncomment if you have an schema file
      - ./mongobi/conf/mongosqld.conf:/home/mongobi/mongosqld.conf
      - ./mongobi/conf/mongo.pem:/home/mongobi/mongo.pem
      - ./mongobi/logs:/logs
    container_name: 'mongobi'
    hostname: 'mongobi'
    ports:
      - 3307:3307
